/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package org.wso2.carbon.la.log.agent.agentConf;

public class ConfigLogAgent {
	private String agentid;
	private String authid;
	private Output output;
    private String authsecret;
	private GroupElement[] groups;

	public void setAgentid(String agentid) {
		this.agentid = agentid;
	}

	public String getAgentid() {
		return agentid;
	}


 	public void setAuthid(String authid) {
		this.authid = authid;
	}

	public String getAuthid() {
		return authid;
	}


 	public void setOutput(Output output) {
		this.output = output;
	}

	public Output getOutput() {
		return output;
	}


 	public void setGroups(GroupElement[] groups) {
		this.groups = groups;
	}

	public GroupElement[] getGroups() {
		return groups;
	}


 	public void setAuthsecret(String authsecret) {
		this.authsecret = authsecret;
	}

	public String getAuthsecret() {
		return authsecret;
	}

}