/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package org.wso2.carbon.la.log.agent.agentConf;

public class File {
	private String path;

 	public void setPath(String path) {
		this.path = path;
	}

	public String getPath() {
		return path;
	}

	private String start_position;

 	public void setStart_position(String start_position) {
		this.start_position = start_position;
	}

	public String getStart_position() {
		return start_position;
	}

}