/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package org.wso2.carbon.la.log.agent.agentConf;

public class Filter {
	private Regex regex;

 	public void setRegex(Regex regex) {
		this.regex = regex;
	}

	public Regex getRegex() {
		return regex;
	}

}