/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package org.wso2.carbon.la.log.agent.agentConf;

public class GroupElement {
	private String name;
	private String version;
	private Config config;

 	public void setVersion(String version) {
		this.version = version;
	}

	public String getVersion() {
		return version;
	}

 	public void setConfig(Config config) {
		this.config = config;
	}

	public Config getConfig() {
		return config;
	}

 	public void setName(String name) {
		this.name = name;
	}

	public String getName() {
		return name;
	}

}