/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package org.wso2.carbon.la.log.agent.agentConf;

public class Input {
	private File file;

 	public void setFile(File file) {
		this.file = file;
	}

	public File getFile() {
		return file;
	}

}