/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package org.wso2.carbon.la.log.agent.agentConf;

public class Loganalyzer {
	private String host;
	private Integer port;
	private String user_name;
	private String password;

 	public void setPassword(String password) {
		this.password = password;
	}

	public String getPassword() {
		return password;
	}

 	public void setUser_name(String user_name) {
		this.user_name = user_name;
	}

	public String getUser_name() {
		return user_name;
	}

 	public void setPort(Integer port) {
		this.port = port;
	}

	public Integer getPort() {
		return port;
	}

 	public void setHost(String host) {
		this.host = host;
	}

	public String getHost() {
		return host;
	}

}