/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package org.wso2.carbon.la.log.agent.agentConf;

public class Output {
	private Loganalyzer loganalyzer;

 	public void setLoganalyzer(Loganalyzer loganalyzer) {
		this.loganalyzer = loganalyzer;
	}

	public Loganalyzer getLoganalyzer() {
		return loganalyzer;
	}

}