/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package org.wso2.carbon.la.log.agent.agentConf;

public class Regex {
	private String[] match;

 	public void setMatch(String[] match) {
		this.match = match;
	}

	public String[] getMatch() {
		return match;
	}

}